openapi: 3.0.0
info:
  title: Agrivium API
  version: 1.0.0
  description: API documentation for the Agrivium System
servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /register:
    post:
      summary: Register a new user
      description: Creates a new user and sends a verification email.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
                - role
              properties:
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  format: password
                  example: "StrongPass123!"
                role:
                  type: string
                  enum: [user, admin]
                  example: user
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Registration failed

  /login:
    post:
      summary: Login user
      description: Authenticates a user and returns a token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  format: password
                  example: "StrongPass123!"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials
